[tool.poetry]
name = "pyskim"
version = "0.1.3"
description = "Quickly create summary statistics for a given dataframe."
license = "MIT"
authors = ["kpj <kim.philipp.jablonski@gmail.com>"]
readme = "README.md"
repository = "https://github.com/kpj/pyskim"

[tool.poetry.dependencies]
python = "^3.7"
pandas = "^1.1.5"
scipy = "^1.5.4"
numpy = "^1.19.4"
click = ">=7.1.2,<9.0.0"
tabulate = "^0.8.7"
ipython = "^7.19.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.0"

[tool.poetry.scripts]
pyskim = "pyskim:main"
